name: Upload artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  upload:
    name: Upload built artefacts
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Build
      run: pwd && make setup && make
    - uses: actions/upload-artifact@v4.4.3
      with:
        # Artifact name
        name: firmware
        path: "*.uf2"
        if-no-files-found: error
        overwrite: true
          
